version: '3.6'
services:
  db:
    image: mysql:5.7.24
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - system_net
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./opt/data:/var/lib/mysql   
networks:
  system_net:
    name: system_net
    driver: bridge
